export const siteConfig = {
  name: 'Telephony Lab',
  title: 'Telephony Lab | 李奔 · 6年 Android Telephony 工程师作品集',
  description:
    '李奔的 Android Telephony 开发工程师作品集，聚焦搜网、数据业务、通话管理、Radio AIDL、运营商认证与多代 ROM 升级交付。',
  url: 'https://dev-ben0915git.github.io/telephony-portfolio',
  author: {
    name: '李奔',
    role: 'Telephony 开发工程师',
    tagline: '6 年 Android Telephony 开发 · 搜网 / 数据业务 / 通话管理 · 高通 / MTK / 海思平台适配',
    location: '成都',
    phone: '17354358970',
    email: '2715605738@qq.com',
    github: 'https://github.com/dev-ben0915git/telephony-portfolio',
    linkedin: '',
    twitter: '',
    resumeUrl: '/telephony-portfolio/resume/telephony-resume.pdf',
    repoUrl: 'https://github.com/dev-ben0915git/telephony-portfolio',
  },
  categories: [
    { key: 'network-search', label: '搜网 / 驻网', color: 'text-tech-yellow' },
    { key: 'data-service', label: '数据业务', color: 'text-tech-green' },
    { key: 'call-module', label: '通话管理', color: 'text-tech-purple' },
    { key: 'radio-aidl', label: 'Radio AIDL', color: 'text-tech-orange' },
    { key: 'certification', label: '认证交付', color: 'text-tech-pink' },
  ],
  nav: [
    { key: 'home', label: '首页', href: '/' },
    { key: 'about', label: '关于我', href: '/about' },
    { key: 'blog', label: '技术博客', href: '/blog' },
    { key: 'projects', label: '项目经历', href: '/projects' },
    { key: 'resume', label: '简历下载', href: '/resume' },
  ],
  stats: [
    { label: '旗舰机型交付', value: '12+', hint: 'Android S 到 W 跨代升级' },
    { label: '客户需求 / 反馈', value: '100+', hint: '需求开发与疑难问题闭环' },
    { label: 'Radio 接口梳理', value: '30+', hint: 'AIDL 升级兼容适配' },
    { label: '交付通过率', value: '100%', hint: '定制需求全流程落地' },
  ],
  keywords: [
    'Telephony',
    'RIL',
    'Radio AIDL',
    'TeleService',
    'Telecom',
    'IMS',
    'VoLTE',
    '搜网',
    '数据业务',
    '短彩信',
    'TelephonyProvider',
    'SIM卡账户',
    'Android',
    'Java',
    'AOSP',
    'Qualcomm',
    'MediaTek',
    'HiSilicon',
    'CTS',
    '运营商认证',
  ],
};

export type SiteConfig = typeof siteConfig;
