export const siteConfig = {
  name: 'Telephony Lab',
  title: 'Telephony Lab | 6年 RIL/IMS/搜网 工程师作品集',
  description:
    '专注于高通 QCRIL、MTK RIL、IMS/VoLTE、搜网排障、Modem Crash 复盘的个人技术作品集，面向 Telephony 方向求职。',
  url: 'https://yourname.github.io/telephony-portfolio',
  author: {
    name: 'Your Name',
    role: 'Senior Telephony / Modem Engineer',
    tagline: '6 年 Android Telephony 栈开发 · 高通 / MTK 双平台 · IMS / VoLTE · RIL 底层',
    location: 'China · Remote / Relocation',
    email: 'your.email@example.com',
    github: 'https://github.com/yourname',
    linkedin: 'https://www.linkedin.com/in/yourname',
    twitter: '',
    resumeUrl: '/resume/telephony-resume.pdf',
    repoUrl: 'https://github.com/yourname/telephony-portfolio',
  },
  categories: [
    { key: 'qcril', label: '高通 QCRIL', color: 'text-tech-orange' },
    { key: 'mtk-ril', label: 'MTK RIL', color: 'text-tech-green' },
    { key: 'ims-volte', label: 'IMS / VoLTE', color: 'text-tech-purple' },
    { key: 'network-search', label: '搜网排障', color: 'text-tech-yellow' },
    { key: 'crash-review', label: 'Crash 复盘', color: 'text-tech-pink' },
  ],
  nav: [
    { key: 'home', label: '首页', href: '/' },
    { key: 'about', label: '关于我', href: '/about' },
    { key: 'blog', label: '技术博客', href: '/blog' },
    { key: 'projects', label: '项目实战', href: '/projects' },
    { key: 'resume', label: '简历下载', href: '/resume' },
  ],
  stats: [
    { label: 'AT 指令处理', value: '200M+', hint: '日均指令包' },
    { label: '搜网耗时优化', value: '-62%', hint: '自研搜网策略' },
    { label: 'IMS 接通率', value: '99.6%', hint: 'VoLTE/VoNR' },
    { label: 'Crash 复盘', value: '80+', hint: 'Modem / RILD' },
  ],
  keywords: [
    'Telephony',
    'RIL',
    'QCRIL',
    'Modem',
    'IMS',
    'VoLTE',
    'VoNR',
    '搜网',
    'AT Command',
    'SIP',
    'SDP',
    'Android',
    'C/C++',
    'Java',
    'Qualcomm',
    'MediaTek',
  ],
};

export type SiteConfig = typeof siteConfig;
